Repository whylabs/whylogs, pull requests merged in 2021-06, with the labels that each got.

#239 add content to sidebar
  src/whylogs/viewer/index.html
Labels: documentation

#240 sidebar update
  src/whylogs/viewer/index.html
  src/whylogs/viewer/js/whylogs-script.js
Labels: enhancement

#236 String features such as lenght, word count, character pos tracking
  Makefile
  examples/String_Features.ipynb
  proto/src/messages.proto
  proto/src/summaries.proto
  src/whylogs/core/columnprofile.py
  src/whylogs/core/datasetprofile.py
  src/whylogs/core/metrics/confusion_matrix.py
  src/whylogs/core/statistics/__init__.py
  src/whylogs/core/statistics/datatypes/__init__.py
  src/whylogs/core/statistics/datatypes/stringtracker.py
  src/whylogs/core/statistics/stringtracker.py
  src/whylogs/util/util_functions.py
  src/whylogs/viz/base.py
  src/whylogs/viz/matplotlib/visualizer.py
  tests/unit/core/statistics/datatypes/test_stringtracker.py
  tests/unit/core/test_columnprofile.py
Labels: feature

#243 serialize delimited format by default
  src/whylogs/app/writers.py
Labels: enhancement, feature

#245 Release 0.4.9-dev0
  .bumpversion.cfg
  Makefile
  docs/conf.py
  pyproject.toml
  src/whylogs/_version.py
Labels: dev-release

#249 update release draft to use correct version number
  .github/release-drafter.yml
Labels: documentation
