Repository whylabs/whylogs, pull requests merged in 2021-11, with the labels that each got.

#345 Add constraint mergeability
  src/whylogs/core/statistics/constraints.py
  tests/unit/core/statistics/test_constraints.py
Labels: enhancement

#352 Update release draft content to correctly lowercase package name.
  .github/release-drafter.yml
Labels: maintenance

#355 Put in some guardrails against overly large confusion matrices
  src/whylogs/core/metrics/confusion_matrix.py
  tests/unit/core/metrics/test_confusion_matrix.py
Labels: bug

#360 Add version info to the commit message for automated PR
  .github/workflows/push_release.yml
Labels: maintenance

#361 Use github env variable for version
  .github/workflows/push_release.yml
Labels: maintenance

#362 Allow manual rerun of failed upload workflow
  .github/workflows/push_release.yml
Labels: maintenance

#365 Fix exception related to logging array like column values
  src/whylogs/core/columnprofile.py
  src/whylogs/core/types/typeddataconverter.py
  tests/unit/core/test_columnprofile.py
  tests/unit/core/types/test_typeddataconverter.py
Labels: bug

#359 Use log_async in WhylabsWriter
  poetry.lock
  pyproject.toml
  src/whylogs/whylabs_client/wrapper.py
  tests/unit/core/test_datasetprofile.py
Labels: performance
