Repository whylabs/whylogs, pull requests merged in 2021-05, with the labels that each got.

#224 add blog post link
  examples/rov_whylogs/README.md
Labels: documentation

#229 Add profile viewer method
  .bumpversion.cfg
  Makefile
  README.md
  docs/conf.py
  images/html_viewer.png
  images/html_viewer_loaded.png
  pyproject.toml
  src/whylogs/_version.py
  src/whylogs/viewer/.prettierignore
  src/whylogs/viewer/.prettierrc.yaml
  src/whylogs/viewer/LICENSE
  src/whylogs/viewer/css/bootstrap.min.css
  src/whylogs/viewer/css/whylogs-styles.css
  src/whylogs/viewer/example/example-invalid-multi-profile.json
  src/whylogs/viewer/example/example-invalid-profile.json
  src/whylogs/viewer/example/example-multi-profile.json
  src/whylogs/viewer/example/example-profile.json
  src/whylogs/viewer/fonts/Asap-Bold.ttf
  src/whylogs/viewer/fonts/Asap-Bold.woff
  src/whylogs/viewer/fonts/Asap-Bold.woff2
  src/whylogs/viewer/fonts/Asap-BoldItalic.ttf
  src/whylogs/viewer/fonts/Asap-BoldItalic.woff
  src/whylogs/viewer/fonts/Asap-BoldItalic.woff2
  src/whylogs/viewer/fonts/Asap-Italic.ttf
  src/whylogs/viewer/fonts/Asap-Italic.woff
  src/whylogs/viewer/fonts/Asap-Italic.woff2
  src/whylogs/viewer/fonts/Asap-Medium.ttf
  src/whylogs/viewer/fonts/Asap-Medium.woff
  src/whylogs/viewer/fonts/Asap-Medium.woff2
  src/whylogs/viewer/fonts/Asap-MediumItalic.ttf
  src/whylogs/viewer/fonts/Asap-MediumItalic.woff
  src/whylogs/viewer/fonts/Asap-MediumItalic.woff2
  src/whylogs/viewer/fonts/Asap-Regular.ttf
  src/whylogs/viewer/fonts/Asap-Regular.woff
  src/whylogs/viewer/fonts/Asap-Regular.woff2
  src/whylogs/viewer/fonts/Asap-SemiBold.ttf
  src/whylogs/viewer/fonts/Asap-SemiBold.woff
  src/whylogs/viewer/fonts/Asap-SemiBold.woff2
  src/whylogs/viewer/fonts/Asap-SemiBoldItalic.ttf
  src/whylogs/viewer/fonts/Asap-SemiBoldItalic.woff
  src/whylogs/viewer/fonts/Asap-SemiBoldItalic.woff2
  src/whylogs/viewer/images/placement-chart.png
  src/whylogs/viewer/images/whylabs-favicon.png
  src/whylogs/viewer/index.html
  src/whylogs/viewer/js/d3.min.js
  src/whylogs/viewer/js/jquery-3.6.0.min.js
  src/whylogs/viewer/js/whylogs-script.js
  src/whylogs/viz/__init__.py
  src/whylogs/viz/browser_viz.py
Labels: feature

#230 Update feature list based on checked inferred types
  src/whylogs/viewer/js/whylogs-script.js
Labels: bug

#234 Fix 232 by storing null_count in schema tracker only
  poetry.lock
  proto/src/messages.proto
  pyproject.toml
  src/whylogs/core/columnprofile.py
  src/whylogs/core/statistics/counterstracker.py
  src/whylogs/core/statistics/schematracker.py
  tests/unit/core/statistics/test_counterstracker.py
  tests/unit/core/statistics/test_schematracker.py
  tests/unit/core/test_columnprofile.py
Labels: bug
