Repository whylabs/whylogs, pull requests merged in 2021-08, with the labels that each got.

#274 link to our main docs website
  docs/index.rst
Labels: documentation

#276 Removing pyarrow and llvmlite from required dependecies
  poetry.lock
  pyproject.toml
Labels: maintenance

#279 Read prediction and target field names from regression metric protobuf
  src/whylogs/core/metrics/regression_metrics.py
  tests/unit/core/metrics/test_model_metrics.py
Labels: bug

#282 Remove reference package
  poetry.lock
  pyproject.toml
Labels: dependencies

#289 [ADD] Google fonts and charts to property panel
  src/whylogs/viewer/index-hbs-cdn-all-in.html
Labels: bug

#288 Add coverage for profile viewer and contraints
  tests/conftest.py
  tests/unit/core/statistics/test_constraints.py
  tests/unit/viz/test_profile_viewer.py
Labels: integrations

#291 Auto bump fix
  pyproject.toml
Labels: bug
