Repository whylabs/whylogs, pull requests merged in 2021-02, with the labels that each got.

#134 ✨ bounding boxes and full local dataset
  .bumpversion.cfg
  docs/conf.py
  requirements-dev.txt
  requirements-test.txt
  requirements.txt
  setup.cfg
  src/whylogs/_version.py
  src/whylogs/app/logger.py
  src/whylogs/app/session.py
  src/whylogs/core/__init__.py
  src/whylogs/core/annotation_profiling.py
  src/whylogs/core/image_profiling.py
  src/whylogs/features/transforms.py
  src/whylogs/io/__init__.py
  src/whylogs/io/file_loader.py
  src/whylogs/io/local_dataset.py
  testdata/fake_dataset/A_target/flower2.jpg
  testdata/fake_dataset/A_target/grace_hopper_517x606.jpg
  testdata/fake_dataset/A_target/yolo_bounding_box.jsonl
  testdata/fake_dataset/B_target/16bit.cropped.tif
  testdata/fake_dataset/B_target/lending-club-accepted-10.csv
  testdata/files/domain.xlsx
  testdata/files/lending-club-accepted-10.csv
  testdata/files/yolo_bounding_box.jsonl
  tests/conftest.py
  tests/unit/app/test_writers.py
  tests/unit/core/test_annotation_profiling.py
  tests/unit/core/test_rect.py
  tests/unit/features/test_image_transforms.py
  tests/unit/io/__init__.py
  tests/unit/io/test_file_loader.py
  tests/unit/io/test_local_dataset.py
Labels: feature

#144 remove a dependency on bleach
  requirements-dev.txt
Labels: dependencies

#163 Handle None case in Confusion matrix merging
  .bumpversion.cfg
  docs/conf.py
  setup.cfg
  src/whylogs/_version.py
  src/whylogs/core/metrics/model_metrics.py
  tests/unit/core/metrics/test_model_metrics.py
Labels: bug
