Repository whylabs/whylogs, pull requests merged in 2022-04, with the labels that each got.

#510 Fixes bumpversion to search and replace
  .bumpversion.cfg
Labels: maintenance

#513 Cache poetry dependencies from lock file
  .github/workflows/python-continuous-integration.yml
  Makefile
Labels: maintenance

#522 Getting Started documentation maintence
  docs/getting_started.rst
Labels: documentation

#542 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: documentation

#543 Enhancing the Error Message on Notebook Profile Vieweer
  src/whylogs/viewer/templates/index-hbs-cdn-all-in-for-jupyter-notebook.html
  src/whylogs/viewer/templates/index-hbs-cdn-all-in-jupyter-bar-chart.html
  src/whylogs/viewer/templates/index-hbs-cdn-all-in-jupyter-differenced-chart.html
  src/whylogs/viewer/templates/index-hbs-cdn-all-in-jupyter-distribution-chart.html
Labels: bug, documentation

#548 Bug/np float issue
  src/whylogs/core/types/typeddataconverter.py
  tests/unit/core/statistics/datatypes/test_floattracker.py
Labels: bug
