Repository whylabs/whylogs, pull requests merged in 2022-10, with the labels that each got.

#920 Bump version to release version
  python/.bumpversion.cfg
  python/Makefile
  python/docs/conf.py
  python/pyproject.toml
  python/tests/smoketest.py
Labels: automated pr

#917 Renames add_metrics to add_metric as it only adds a singular metric
  python/whylogs/api/logger/result_set.py
Labels: bug, python

#936 Bump version to release version
  python/.bumpversion.cfg
  python/Makefile
  python/docs/conf.py
  python/pyproject.toml
  python/tests/smoketest.py
Labels: automated pr

#934 Adjusting overall README examples and integrations
  python/README.md
  python/docs/examples.md
  python/docs/examples.rst
  python/docs/index.md
  python/examples/README.md
  python/examples/basic/README.md
  python/examples/integrations/README.md
  python/examples/integrations/writers/Writing_Reference_Profiles_to_WhyLabs.ipynb
Labels: documentation

#941 [Fix] Fixing broken links on readme
  python/examples/README.md
Labels: bug, work-in-progress

#928 Avoid KeyError indexing into pandas DataFrame
  python/whylogs/core/dataset_profile.py
Labels: bug

#939 Java Loggers
  java/core/src/main/java/com/whylogs/api/logger/Logger.java
  java/core/src/main/java/com/whylogs/api/logger/TransientLogger.java
  java/core/src/main/java/com/whylogs/api/logger/resultsets/ProfileResultSet.java
  java/core/src/main/java/com/whylogs/api/logger/resultsets/ResultSet.java
  java/core/src/main/java/com/whylogs/api/logger/rollingLogger/Scheduler.java
  java/core/src/main/java/com/whylogs/api/logger/rollingLogger/TimedRollingLogger.java
  java/core/src/main/java/com/whylogs/api/writer/Writable.java
  java/core/src/main/java/com/whylogs/api/writer/Writer.java
  java/core/src/main/java/com/whylogs/api/writer/WritersRegistry.java
  java/core/src/main/java/com/whylogs/core/DatasetProfile.java
  java/core/src/main/java/com/whylogs/core/schemas/DatasetSchema.java
  java/core/src/test/java/com/whylogs/api/logger/TestLogger.java
  java/core/src/test/java/com/whylogs/api/logger/TestRollingLogger.java
Labels: java
