Repository whylabs/whylogs, pull requests merged in 2022-07, with the labels that each got.

#623 Log Rotation Example
  python/docs/examples.rst
  python/examples/advanced/Log_Rotation_for_Streaming_Data/Streaming_Data_with_Log_Rotation.ipynb
Labels: documentation

#688 Adds in Release Drafter to v1
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, integration

#696 fix contribution.md hyperlink on readme
  python/README.md
Labels: documentation

#691 Adds the BumpVersion for our CICD workflow
  python/.bumpversion.cfg
  python/Makefile
  python/poetry.lock
Labels: enhancement, integration

#698 Updates links for readme, merges it in, and removes an unavailable co…
  .github/DEVELOPMENT.md
  python/README.md
Labels: documentation

#702 Orders all views columns before sending to pandas
  python/tests/core/view/test_dataset_profile_view.py
  python/whylogs/core/view/dataset_profile_view.py
Labels: enhancement

#685 Flask Integration of whylogs and WhyLabs Notebook
  python/.pre-commit-config.yaml
  python/docs/examples.rst
  python/examples/integrations/flask_streaming/.dockerignore
  python/examples/integrations/flask_streaming/.env
  python/examples/integrations/flask_streaming/Dockerfile
  python/examples/integrations/flask_streaming/api/__init__.py
  python/examples/integrations/flask_streaming/api/utils.py
  python/examples/integrations/flask_streaming/api/views.py
  python/examples/integrations/flask_streaming/app.py
  python/examples/integrations/flask_streaming/assets/WhyLabs_profile.png
  python/examples/integrations/flask_streaming/assets/flask_whylogs_whylabs_flow.jpeg
  python/examples/integrations/flask_streaming/autoapp.py
  python/examples/integrations/flask_streaming/environment.yml
  python/examples/integrations/flask_streaming/extensions.py
  python/examples/integrations/flask_streaming/flask_with_whylogs.ipynb
  python/examples/integrations/flask_streaming/model.joblib
  python/examples/integrations/flask_streaming/requirements.txt
  python/examples/integrations/flask_streaming/schemas.py
  python/examples/integrations/flask_streaming/settings.py
  python/examples/integrations/flask_streaming/swagger.yaml
  python/examples/integrations/flask_streaming/utils.py
  python/poetry.lock
  python/pyproject.toml
  python/test_notebooks/notebook_tests.py
Labels: documentation
