Repository whylabs/whylogs, pull requests merged in 2022-08, with the labels that each got.

#725 Add callback for rolling logger profile writes
  python/tests/api/logger/test_rolling.py
  python/whylogs/api/logger/rolling.py
Labels: feature

#741 Draft: Updates the ReadMe for Java
  java/README.md
Labels: documentation

#766 Add Twine to dev dependency
  python/poetry.lock
  python/pyproject.toml
Labels: bug

#757 Aggregator for Metric Components
  java/core/src/main/java/com/whylogs/core/metrics/aggregators/AggregatorRegistry.java
  java/core/src/main/java/com/whylogs/core/metrics/aggregators/IAggregator.java
  java/core/src/main/java/com/whylogs/core/metrics/aggregators/NumberSumAggregator.java
  java/core/src/main/java/com/whylogs/core/metrics/components/IntegralComponent.java
  java/core/src/main/java/com/whylogs/core/metrics/components/MaxIntegralComponent.java
  java/core/src/main/java/com/whylogs/core/metrics/components/MetricComponent.java
  java/core/src/main/java/com/whylogs/core/metrics/components/MinIntegralComponent.java
  java/core/src/test/java/com/whylogs/core/metrics/aggregators/TestAggregatorRegistry.java
  java/core/src/test/java/com/whylogs/core/metrics/aggregators/TestSumAggregators.java
Labels: java
