Repository whylabs/whylogs, pull requests merged in 2023-05, with the labels that each got.

#1229 Bump version to release version 1.1.39
  python/.bumpversion.cfg
  python/Makefile
  python/docs/conf.py
  python/pyproject.toml
  python/tests/smoketest.py
Labels: automated pr

#1241 Bump version to release version 1.1.41
  python/.bumpversion.cfg
  python/Makefile
  python/docs/conf.py
  python/pyproject.toml
  python/tests/smoketest.py
Labels: automated pr

#1253 Bump version to release version 1.1.42
  python/.bumpversion.cfg
  python/Makefile
  python/docs/conf.py
  python/pyproject.toml
  python/tests/smoketest.py
Labels: automated pr

#1162 Multi-column UDF support
  python/tests/experimental/core/metrics/test_udf_metric.py
  python/tests/experimental/core/test_udf_schema.py
  python/whylogs/api/logger/logger.py
  python/whylogs/api/logger/segment_processing.py
  python/whylogs/core/dataset_profile.py
  python/whylogs/core/resolvers.py
  python/whylogs/core/schema.py
  python/whylogs/experimental/core/metrics/udf_metric.py
  python/whylogs/experimental/core/udf_schema.py
Labels: feature, experimental

#1255 change alias to None if empty string
  python/whylogs/api/writer/whylabs.py
Labels: bug

#1256 Add factory constraints: condition count below
  python/examples/advanced/Metric_Constraints_with_Condition_Count_Metrics.ipynb
  python/examples/basic/Constraints_Suite.ipynb
  python/tests/core/constraints/factories/test_condition_count_metrics.py
  python/whylogs/core/constraints/factories/__init__.py
  python/whylogs/core/constraints/factories/condition_counts.py
Labels: enhancement

#1260 Bump version to release version 1.1.43
  python/.bumpversion.cfg
  python/Makefile
  python/docs/conf.py
  python/pyproject.toml
  python/tests/smoketest.py
Labels: automated pr
